# Generated by Django 2.2.10 on 2020-02-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(default='', upload_to='', verbose_name='image1'),
        ),
    ]
